### ISSUE TITLE
hi, where is the code of computing social-attention and the code of updating the policy ? thanks.

### ISSUE THREAD

**Issue by siatjia** [eleurent/rl-agents#102]
python experiments.py evaluate configs/IntersectionEnv/env.json \
                               configs/IntersectionEnv/agents/DQNAgent/ego_attention_2h.json \
                               --train --episodes=4000 --name-from-config

when i debug, i can not find it.

**Comment by eleurent** [comment]
Social attention: the architecture is in https://github.com/eleurent/rl-agents/blob/63d3734123fffcfcc84d9fc84195256a94d74638/rl_agents/agents/common/models.py#L157

Policy update: https://github.com/eleurent/rl-agents/blob/63d3734123fffcfcc84d9fc84195256a94d74638/rl_agents/agents/deep_q_network/pytorch.py#L14

**Comment by siatjia** [comment]
Thanks. good job.
