### ISSUE TITLE
'Adam' object has no attribute 'get_updates'

### ISSUE THREAD

**Issue by AashiDutt** [eleurent/rl-agents#103]
When applying dqn.fit, I'm getting the following error: 

**### AttributeError: 'Adam' object has no attribute 'get_updates'**

**_Here is my code for reference:_**

dqn=DQNAgent(model=model, memory=memory, policy=policy, enable_dueling_network=True, dueling_type='avg', nb_actions=actions,nb_steps_warmup=1000)

dqn.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    metrics=['accuracy']
)

dqn.fit(env,nb_steps=5000,visualize=False, verbose=1)

**Comment by eleurent** [comment]
Hi,
If you're using this library, that's not how DQN training work.
You should simply use the [Evaluation](https://github.com/eleurent/rl-agents/blob/63d3734123fffcfcc84d9fc84195256a94d74638/rl_agents/trainer/evaluation.py#L23C7-L23C17) class which takes an agent and env, and run `evaluation.train()`

**Comment by AashiDutt** [comment]
Thank You, I'll give it a try.
