### ISSUE TITLE
Agent compatibility for IntersectionEnv multiagent env

### ISSUE THREAD

**Issue by HeapSoil** [eleurent/rl-agents#105]
Hi, thanks for the great work which really helps for rl beginner like me.
I want to try out different approaches for the multi-agent IntersectionEnv (the config is `IntersectionEnv/env_multi_agent.json` ), and I notice there are differenct agent configs in the IntersectionEnv folder. But when I tried to run some of them it didn't go well.
Before further debugging, I wonder if all of them (DeterministicPlanner, DiscreteRobustPlanner, FTQ, OpenLoop, Robust, ValueIteration) are compatiable with the multi-agent version of IntersectionEnv? 

Thanks again!

**Comment by eleurent** [comment]
Hi,
No, only the DQNAgent is compatible with multiagent environments unfortunately.
The other agents (like tree-based planners) could be adapted to a multi-agent setting, but the search space would be quite large (combination of each agent's sequences of actions), so it would probably require a large computational cost. Or we could approximate the solution as a combination of independent single-player decisions, but this requires that each agent makes assumption on the behaviours of other agents etc, so it would require some work and would not work out of the box for any env.

**Comment by HeapSoil** [comment]
Oh thanks for the explanation, maybe I should try other ways to implement multi-agent intersection algorithm.
I'm closing this issue.
