### ISSUE TITLE
How can I obtain the accelaration information of vehicles? 

### ISSUE THREAD

**Issue by LemonPasserby** [eleurent/rl-agents#107]
I wanna add accelaration information into the observation spaces and  monitor the accelaration changes. But i didn't find the function to calculate accerations of vehicles. Looking forward to you reply！！

**Comment by LemonPasserby** [comment]
The longitudinal accelaration is mainly needed.

**Comment by eleurent** [comment]
You can get the current longitudinal acceleration with `env.vehicle.action['acceleration']`.

**Comment by LemonPasserby** [comment]
i get it, thanks. I'll close the issue.
