### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by 6Lackiu** [eleurent/rl-agents#112]
Hello! I trained the model using `python experiments.py evaluate configs/IntersectionEnv/env.json configs/IntersectionEnv/agents/DQNAgent/ego_attention_2h.json --train --episodes=4000`, but the training results are not as good as those presented in your paper. What could be the issue?
![image](https://github.com/eleurent/rl-agents/assets/52661423/9d688a97-8a35-434f-beae-774334546528)
![image](https://github.com/eleurent/rl-agents/assets/52661423/2b14371c-2ba6-45ad-b55a-a55d67beaf3f)

**Comment by eleurent** [comment]
Note that in my paper, results were averaged across many random seeds, which smoothes the reward vs steps curve, but each runs typically has more variance across steps (each collision creates a large drop, so returns tend to be discontinuous/noisy). But when aggregating over multiple episodes, we should see the same effect that the mean reward moves from ~2 to ~6, which might be the case in your run? Can you try to increase the smoothing on your tensorboard?

If you still think the results are worse, then there might indeed be a regression, which is always possible (I think I made some small changes to the vehicle dynamics, aimed at improving other environments). You can try to sync both repos to some older version from e.g. dec 2019 and run training again.

**Comment by 6Lackiu** [comment]
Thank you for your explanation! I'll continue trying.
