### ISSUE TITLE
Display vehicle trajectory

### ISSUE THREAD

**Issue by 6Lackiu** [eleurent/rl-agents#114]
Hi! I would like to ask how is a video with vehicle trajectory generated like this?
![image](https://github.com/eleurent/rl-agents/assets/52661423/66309d94-6b6c-4c41-88f1-c464819e200a)

**Comment by eleurent** [comment]
To show vehicle trajectories, you should [configure the environment](https://highway-env.farama.org/quickstart/#configuring-an-environment) with {'show_trajectories': True}

For example, `env = gym.make('intersection-v0', config={'show_trajectories': True})`
Or if you're using this repo's experiments.py script, simply edit the scripts/configs/IntersectionEnv/env.json (or whichever variant you're using) to add `"show_trajectories": True,`

**Comment by 6Lackiu** [comment]
Got it! Thank you!
