### ISSUE TITLE
Add custom env

### ISSUE THREAD

**Issue by arita37** [eleurent/rl-agents#22]
Is it possible to add custom environmment.

**Comment by eleurent** [comment]
Absolutely, see for instance the configuration file for [highway-env](https://github.com/eleurent/highway-env), a custom environment: [scripts/configs/HighwayEnv/env.json](https://github.com/eleurent/rl-agents/blob/master/scripts/configs/HighwayEnv/env.json)

```
{
    "id": "highway-v0",
    "import_module": "highway_env"
}
```

The `import_module` field must be used to import the environment module, and the `id `field is the name of the environment, used as `env = gym.make(config.id)`

**Comment by arita37** [comment]
If we dont want to register in gym,
How can we do it ?

**Comment by eleurent** [comment]
Then you should modify the script `scripts/experiments.py`
It is only meant as an interface between the Evaluation class, that accepts an environment and an agent, and the json configuration files. The environment is instanciated with a `load_environment()` call (that internally performs a `gym.make(env_config["id"])`), but you can replace this code with your own way of creating an environment.

**Comment by arita37** [comment]
Hello,
This framework is very good.
Believe we should simplify the way to create an an Env.

What about refactoring 
    1 python file == 1 environmment setup
    (with methods,...)

So when adding new env, we dont have to change all other code....

I can provide some template for this code pattern.

Can we discuss over gitter ?

**Comment by eleurent** [comment]
Thanks @arita37!
I think the current way to create an Env is already very simple and generic: 1 environment setup = 1 json configuration file.

I don't really want to add a new python file (=more code) each time I want to add an environment.
I recognize that the current solution requires gym registration, but it is a very common and well-established interface.

But I'd be happy to discuss if you have a better idea.

**Comment by arita37** [comment]
Hello,
Can we discuss over gitter.im or skype ?

My question what if we have a custom environmement, not in gym, for a specific problem.

Process is not so clear.
Do we need to create in gym 1st ?

**Comment by eleurent** [comment]
I invited you on gitter: https://gitter.im/rl-agents/community
Otherwise, my Skype is @eleurent
