### ISSUE TITLE
ImportError: No module named 'rl_agents.agents.budgeted_ftq'

### ISSUE THREAD

**Issue by autonomobil** [eleurent/rl-agents#23]
Hey, I installed the highway-env via :
`pip3 install --user git+https://github.com/eleurent/highway-env`
and the rl-agents with:
`pip3 install --user git+https://github.com/eleurent/rl-agents`

When I run 
`python3 experiments.py benchmark configs/RoundaboutEnv/benchmark_robust_control.json \ --test --episodes=100 --processes=4`

 I get the error:
`ImportError: No module named 'rl_agents.agents.budgeted_ftq'`

What could cause this problem?

**Comment by eleurent** [comment]
That is strange, as this module does exist here: https://github.com/eleurent/rl-agents/tree/master/rl_agents/agents/budgeted_ftq

I just tried it and everything seems to be working, so it must be related to your setup. Could you try to update the module with: 
`pip3 install --user git+https://github.com/eleurent/rl-agents --upgrade`
and try again?

**Comment by cynddl** [comment]
Same issue here, even after upgrading. Using _rl-agents-1.0.dev0_ from the master branch.

**Comment by eleurent** [comment]
@cynddl @autonomobil Can you update the package with ` pip3 install --user git+https://github.com/eleurent/rl-agents --upgrade` and confirm that the fix works properly?
