### ISSUE TITLE
Hi，the problem of the reward function.

### ISSUE THREAD

**Issue by zhangxinchen123** [eleurent/rl-agents#30]
I'm very sorry to disturb you again.
In the highenv_env, the reward function define that the it's relate with the collision, the agent on the right lane ,and the high velocity reward. I can understand that the collision reward is that when the agent collide with other vehicle，we can get a collision reward and the simulation ends，but about the high velocity reward, I have two questions:
The first is that in the high velocity reward,  i notice that a variable which named “SPEED_COUNT” and it‘s defined in the file vehicle/control.py, and it used to speed_to_index, but i don't know the meaning of the variable. 
The second is that how often the high velocity reward is returned when the agent is trained in the environment ？It’s maybe a state gets rewarded once, a second, or depends on the last state?Can you tell me in which file do these problems are reflected? Thank you very much！

**Comment by eleurent** [comment]
*  i notice that a variable which named “SPEED_COUNT” but i don't know the meaning 

It is used to discretise the space of velocities between SPEED_MIN and SPEED_MAX, so that discrete actions FASTER and SLOWER can be used.
It is used in the reward function to compute a "velocity ratio" between 0 (min speed) and 1 (max speed) and the corresponding reward.

* how often the high velocity reward is returned when the agent is trained in the environment ？

the `_reward()` function is called at every `step(action)` in `envs/abstract.py` (= every action = every second)

**Comment by zhangxinchen123** [comment]
>     * i notice that a variable which named “SPEED_COUNT” but i don't know the meaning
> 
> 
> It is used to discretise the space of velocities between SPEED_MIN and SPEED_MAX, so that discrete actions FASTER and SLOWER can be used.
> It is used in the reward function to compute a "velocity ratio" between 0 (min speed) and 1 (max speed) and the corresponding reward.
> 
>     * how often the high velocity reward is returned when the agent is trained in the environment ？
> 
> 
> the `_reward()` function is called at every `step(action)` in `envs/abstract.py` (= every action = every second)

Thanks for you help! I wish every success in your future !

**Comment by zhangxinchen123** [comment]
>     * i notice that a variable which named “SPEED_COUNT” but i don't know the meaning
> 
> 
> It is used to discretise the space of velocities between SPEED_MIN and SPEED_MAX, so that discrete actions FASTER and SLOWER can be used.
> It is used in the reward function to compute a "velocity ratio" between 0 (min speed) and 1 (max speed) and the corresponding reward.
> 
>     * how often the high velocity reward is returned when the agent is trained in the environment ？
> 
> 
> the `_reward()` function is called at every `step(action)` in `envs/abstract.py` (= every action = every second)

Another question is that in the highway_env/envs/common/observation.py, the feature of the class KinematicObservation is  ['presence', 'x', 'y', 'vx', 'vy'], i understand that the presence mean whether the vehicle exist, exist is "1", otherwise "0". the "x" and "y" means the relative distance between Longitudinal and Horizontal, the "vx" and "vy" means the relative velocity between Longitudinal and Horizontal, is this right ? thanks a lot !

**Comment by eleurent** [comment]
You too!
