### ISSUE TITLE
 Indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead

### ISSUE THREAD

**Issue by zhaoworking** [eleurent/rl-agents#33]
`/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.`
When I test the  environment `env_easy.json` with the agent `baseline.json`, just to find this tip occurs repetitively on my screen .How can I ignore that or let it disappeared frommy screen?

**Comment by eleurent** [comment]
Thanks for the feedback, I replaced torch.uint8 by torch.bool everywhere so it should be fine
