### ISSUE TITLE
Analyze Data

### ISSUE THREAD

**Issue by mkapron9** [eleurent/rl-agents#37]
Hello,
I was able to run an experiment with the HighwayEnv successfully and now I am trying to analyze the data. Unfortunately I cannot seem to figure it out. I am running the command

`!python3 scripts/analyze.py run path/to/data/openaigym.episode_batch.0.953.stats.json`

but I keep getting the following error

****
INFO:root:Fetching data in out/HighwayEnv/DQNAgent/run_20200413-214123_953/run/openaigym.episode_batch.0.953.stats
INFO:root:Found 0 runs.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'episode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rl-agents/scripts/analyze.py", line 131, in <module>
    main()
  File "rl-agents/scripts/analyze.py", line 36, in main
    RunAnalyzer(opts['<run_folder>'], out=opts["--out"], episodes_range=episodes_range)
  File "rl-agents/scripts/analyze.py", line 49, in __init__
    self.analyze()
  File "rl-agents/scripts/analyze.py", line 97, in analyze
    self.find_best_run()
  File "rl-agents/scripts/analyze.py", line 111, in find_best_run
    df = df[df["episode"] == df["episode"].max()].sort_values(criteria, ascending=ascending)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'episode'
****

I assume the issue with pandas stems from the fact that it says "Found 0 runs" and therefore could not pass that data on. I'm not too familiar with json files and I've tried running 

`!python3 scripts/analyze.py run path/to/data/`

among many others things to get it to work but have not been successful. Could you help me figure out how to analyze the data? Are there specific files that need to be in the same folder as the stats.json?

**Comment by mkapron9** [comment]
Of course I figured it out after I finally decided to post a question. To anyone that has the same issue, the path/to/data need to stop at the agent folder. So In my case it was out/HighwayEnv/DQNAgent

Hope this helps someone

**Comment by eleurent** [comment]
If I remember well, it should also work if you provide the path of the run (the directory containing the manifest and .stats file), rather than that of the agent (which contains all the runs).

**Comment by mkapron9** [comment]
Thank you for your feedback! I will definitely try that as well. Additionally, I was wondering if there was a way to analyze the data from multiple agents to compare to one another on the same set of plots. Is this possible with the current program or would I need to modify it a little?

**Comment by eleurent** [comment]
The easiest way is probably to put all the runs directories in some parent folder that you provide to analysis.py script. 

You can use benchmark of several agent by listing their configurations in a benchmark.json file. Running it with experiments.py generates a list of runs (one for each agent), and a summary file containing the paths to each run directory. Then, using the summary file in analyze.py loads all runs and plots all agents on the same graphs.

Of course, you can always adapt the script to your particular needs and requirements.

**Comment by mkapron9** [comment]
I will try that. I was also looking into using benchmark last night but I was getting an error when I was trying to run the FTQ benchmark.

`AssertionError: daemonic processes are not allowed to have children`

I dug around for quite a while but was unable to resolve it

**Comment by eleurent** [comment]
Ah, yes...
I used to use multiprocessing to run benchmarks (1 process per agent to run). But since then I implemented the FTQ (and other agents) that collects a batch of data with the current policy by dispatching workers on several processes as well.

So the issue is that multiprocessing cannot be used both in one agent and between several agents.
You can try to add the option `--processes=1`, it might solve it.

This is why in practice I don't use this benchmark option so much anymore, I rather run each agent config separately, and if I want to do several in parallel I use tmux and run the experiments.py script several times (which will work well even with several FTQ agents).

**Comment by mkapron9** [comment]
Oh that makes sense. I was able to run the benchmarks and got some good plots. Thank you for your help. One quick question, what is the meaning of the "crashed" metric? It seems to jump around a bit between 0 and 1 with increments of 0.1. I couldn't find how that was being calculated.

**Comment by mkapron9** [comment]
With more digging I figured out since analyze sub samples by default that "crashes" is just an average over that last 10 episodes

**Comment by eleurent** [comment]
Yes exactly, otherwise you get noisy plots difficult to read. 
Here, you can read it as a probability of having a collision in 10 episodes.
