### ISSUE TITLE
Questions about selection_rule in OPD

### ISSUE THREAD

**Issue by marooncn** [eleurent/rl-agents#46]
Hi, in _selection_rule_ function in _deterministic.py_, it chooses the max _value_upper_, but in the OPD paper, the algorithm expands according to the max _value_upper_ while it chooses action according to the _value_lower_.
![2020-08-06 11-51-51屏幕截图](https://user-images.githubusercontent.com/29606478/89488707-48f44880-d7db-11ea-9bd6-4c22c960490e.png)

**Comment by eleurent** [comment]
Oh no, you're right! 😮 Thank you so much for spotting this.
It is a regression, due to a poor choice of function name `get_value()`, which used to refer to the value *lower* bound, and was recently changed to the value *upper* bound during some refactoring.
