### ISSUE TITLE
Some questions about ego attention DQN

### ISSUE THREAD

**Issue by Exasor** [eleurent/rl-agents#60]
Hi, I read your paper _Social Attention for Autonomous Decision-Making in Dense Traffic_, but I am not clear about why to fed tensors to several heads, and how to select the number of head? In HighwayEnv the number of heads is 2, I wonder if I should change this number in MergeEnv.

**Comment by eleurent** [comment]
Hi, 
Using several heads can allow them to specialize and attend to different parts of the input data, and it has shown to be beneficial in some use cases. However, the number of heads can be considered as a hyperparameter, and I don't know of any good tuning rule except for manual/grid search... On the intersection task, I think that I tried 2, 4 and 8 heads without seeing any significant effect (but 2 was better than 1). Also, note that with the current implementation, the dimensions of the attention features are shared between the heads, so (all things being equal) having more heads also means having smaller heads.

**Comment by Exasor** [comment]
I will try it, thanks a lot!!
