### ISSUE TITLE
Model Weights and Biases - Histogram Tensorboard

### ISSUE THREAD

**Issue by skynox03** [eleurent/rl-agents#64]
Hi Eluerent,

I have some doubts regarding the analyse of weights and biases:

1) I wanted to know, how can I create a histogram of weights and biases, in order to better visualize the trained model?

2) Is it possible to print the parameters (weights and biases) ?

3) Is there also any other way to analyse weights and biases distribution?

It would be great if you could answer them! :D

**Comment by eleurent** [comment]
Hi,

1.  You should edit the agent code to include something like this:
```
for name, param in self.model.named_parameters():
    self.writer.add_histogram(f'{name}_weight', param.weight.detach().cpu().numpy(), episode)
    self.writer.add_histogram(f'{name}_bias', param.bias.detach().cpu().numpy(), episode)
```
2. Same thing, just use print() or logger.info() instead of writer.add_histogram()
3. Possibly, but not that I know of...

**Comment by eleurent** [comment]
yeah sorry, I didn't really check my code, it was just to give you the main idea.

`param.weight` and `param.bias` do not exist because `param` already iterates all weights and biases, so simply do:
```
self.writer.add_histogram(f'{name}_weight', param.data, episode)
```
and it should work I guess

**Comment by skynox03** [comment]
Okay, I will try it!
