### ISSUE TITLE
[Question] Rationale behind visualization of confidence ellipses 

### ISSUE THREAD

**Issue by GPrathap** [eleurent/rl-agents#65]
Could you explain the rationale behind applying the following operation? 

https://github.com/eleurent/rl-agents/blob/5e396546fa868ab7ab360caa142bddfd884a26a2/rl_agents/agents/robust/graphics/robust_epc_graphics.py#L106

rather than taking  `ell_radius_x = np.sqrt(cov[0, 0]),  ell_radius_y = np.sqrt(cov[1, 1])`

**Comment by eleurent** [comment]
Hi @GPrathap,
The solution that you propose would not account for the cross-correlation term cov[0, 1].

See e.g. [this post](https://carstenschelp.github.io/2018/09/14/Plot_Confidence_Ellipse_001.html) for more details (I'll add the reference to the documentation)

**Comment by GPrathap** [comment]
@eleurent  thank you for your quick reply, yeah that makes sense, thank you. 
Yet, let's say `cov` is a 3x3 matrix, or any other size, is the following representation valid?

```
U, s, rotation = linalg.svd(cov)
radii = 1.0/np.sqrt(s)
u = np.linspace(0.0, 2.0 * np.pi, 100)
v = np.linspace(0.0, np.pi, 100)
x = radii[0] * np.outer(np.cos(u), np.sin(v))
y = radii[1] * np.outer(np.sin(u), np.sin(v))
z = radii[2] * np.outer(np.ones_like(u), np.cos(v))
for i in range(len(x)):
    for j in range(len(x)):
        [x[i,j],y[i,j],z[i,j]] = np.dot([x[i,j],y[i,j],z[i,j]], rotation) + center
ax.plot_wireframe(x, y, z,  rstride=4, cstride=4, color='r', alpha=0.2)
```

Source: https://stackoverflow.com/questions/7819498/plotting-ellipsoid-with-matplotlib

**Comment by eleurent** [comment]
Yes, that would work as well!
These are two different approached for the same thing, though the one that I use in rl-agents is a bit more specific to 2D ellipses, and useful if you want to use the Ellipse patch directly, rather than a plot (wireframe) of a bunch of X/Y(/Z) points sampled uniformly on the ellipse(oid)

**Comment by GPrathap** [comment]
yeah thanks
