### ISSUE TITLE
ImportError: cannot import name 'RecordVideo'

### ISSUE THREAD

**Issue by skonwa** [eleurent/rl-agents#78]
When I run Ego-attention in Pycharm Terminal with following command "python experiments.py evaluate configs/IntersectionEnv/env.json configs/IntersectionEnv/agents/DQNAgent/ego_attention_2h.json --train --episodes=4000 --name-from-config",it come up with this error:ImportError: cannot import name 'RecordVideo',what should I do?

**Comment by eleurent** [comment]
This is because the `Monitor` wrapper has been replaced by `RecordVideo` and `RecordEpisodeStatistics` in the latest gym versions.
So you should simply update to gym>=0.20

**Comment by skonwa** [comment]
Thanks for your help！I will try it.
