### ISSUE TITLE
Recommended gym and highway-env versions

### ISSUE THREAD

**Issue by ShirelJosef** [eleurent/rl-agents#88]
Hey
Gym api changed recently
What are the recommended gym and highway versions?
Thanks

**Comment by eleurent** [comment]
The development version of highway-env (this git repository) uses the latest gym version, gym>=0.26.
Previous releases are compatible with previous versions of gym, gym<=0.25

**Comment by tvidano** [comment]
I think the tree-search abstract class in the Master branch has not been made compatible. [rl_agents/agents/tree_search/abstract.py#L159-L162](https://github.com/eleurent/rl-agents/blob/afd12de0174c355611a6e25cba0c0d269c15a39e/rl_agents/agents/tree_search/abstract.py#L159-L162)

**Comment by eleurent** [comment]
Good point, just updated rl-agents to follow gym>-0.26 interface as well.
