### ISSUE TITLE
Display vehicle attention and distribution of actions only works in episode 0

### ISSUE THREAD

**Issue by Karim-SUN** [eleurent/rl-agents#96]
Hi, eleurent.
I've tried ego-attention agent in IntersectionEnv and everything worked fine, except that the pygame window only displays attention values and distribution of actions in episode 0 (picture below)
![捕获](https://user-images.githubusercontent.com/66453425/227498060-7f6e54da-93c0-489c-a4f8-3590eba8b67f.PNG)

and after that every time the visualization window shows up and it only displays the environment (like picture below)
![捕获1](https://user-images.githubusercontent.com/66453425/227498564-271778cf-3070-41b3-bc3a-62d57bd66aa1.PNG)

In debug mode I've noticed the pygame window successfully doubled in width before episode 0 started and close normally after episode is done. After that in episode 1, 8, 27... (when the episode should be displayed accordingly) the pygame window just contains the environment.
I assume it has something to do with the `agents/deep_q_network/graphics.py` in function `display`, but I don't know how to correct this.
Appreciate your help :)

**Comment by eleurent** [comment]
You are right, this was caused by changes in how gym/gymnasium handles the recording of videos at the end of episodes.
This should now be fixed at HEAD, so you need to install the latest version (upgrade rl-agents, uninstall highway-env, clone the repo and pip install .)
